

export const ADD_FEEDBACK = 'ADD_MESSAGE';
export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const FEEDBACK_FAILED = 'FEEDBACK_FAILED';

export const ADD_STUDENTS = 'ADD_STUDENTS';
export const STUDENTS_LOADING = 'STUDENTS_LOADING';
export const STUDENTS_FAILED = 'STUDENTS_FAILED';
